Varenthein/WDP-2101-01

- src/components/common/ProductBox/ProductBox.js
- src/components/common/ProductBox/ProductBox.module.scss
- src/redux/initialState.js
Following changes were made:
- Inline style for ProductBox component with background-image property was added
- Image source for each product in initialState was set
- ProductBox styles for background image were changed
> [WDP210101-1] Add Image for each product box

- package-lock.json
- src/components/common/ProductBox/ProductBox.js
- src/components/common/ProductBox/ProductBox.module.scss
1.  "Quick View" and "ADD TO CARD" buttons are visible on root hover.
2.  "price" changes background color on root hover.
> WDP210101-4 Added hover effects to Buttons

- src/components/layout/CompanyClaim/CompanyClaim.module.scss
- Styles were updated
- Width: 55px can contain max. 5 digits.
> [WDP210101-2] Update styles for cart count

- src/components/common/Button/Button.module.scss
- src/components/common/FeatureBox/FeatureBox.module.scss
- src/components/common/ProductBox/ProductBox.js
- src/components/common/ProductBox/ProductBox.module.scss
- src/components/features/NewFurniture/NewFurniture.module.scss
- src/components/features/ProductSearch/ProductSearch.module.scss
- src/components/layout/CompanyClaim/CompanyClaim.module.scss
- src/components/layout/Footer/Footer.module.scss
- src/components/layout/MenuBar/MenuBar.module.scss
- src/components/layout/TopBar/TopBar.module.scss
- src/styles/settings.scss
What do do:
- sort colours used in project
- assign each colour to particular section of page to make it more "customizable" for client
How I've done it:
- Put all values into scale and all hue colours after on the top of the file
- After this,  divide all files into sections and assign colours and values to them
- This way, client has huge customization ability in one file
> [WDP210101-8] Update colors variables for entire project

- src/components/layout/CompanyClaim/CompanyClaim.js
- src/components/layout/CompanyClaim/CompanyClaim.module.scss
- src/components/layout/TopBar/TopBar.js
- src/components/layout/TopBar/TopBar.module.scss
- src/styles/mixins.scss
What do do:
- Add media queries for topbar and banner sections with client's constrains about styles
How I've done it:
- Create new mixin file with inline media queries for mobile-small, mobile and tablet screens (excluding landscapes)
- Update Topbar styles: dropdowns stay the same, hide text from logo and register - only icons left
- Update Banner styles: logo on the left, cart on the right top, phone on the right down
> [WDP210101-15] RWD topbar & banner

- src/components/common/ProductBox/ProductBox.js
- src/components/common/ProductBox/ProductBox.module.scss
- src/components/common/ProductBox/ProductBoxContainer.js
- src/components/features/NewFurniture/NewFurniture.js
- src/redux/productsRedux.js
- src/redux/store.js
- yarn.lock
-  Added ProductBoxContainer,
-  Added two action types in productsRedux.js 'addFavorite'/'removeFavorite' to toggle favorite products prop of boolean val.
-  Changed the color of active/pressed favorite button to $btn-dark-background which also was its color on hover.
> [WDP210101-11] Added Favorite Actions/Toggle

- src/components/features/Promotions/Promotions.js
- src/components/features/Promotions/Promotions.module.scss
- src/components/features/Promotions/PromotionsContainer.js
- src/components/views/Homepage/Homepage.js
- src/redux/initialState.js
- src/redux/promotionsRedux.js
- src/redux/store.js
- src/styles/settings.scss
What to do:
- Create promotions component and add styles based on design
- Load all data from state
- *[WDP210101-26] Create RWD for promotions component is inclided, on small screens all items should be in columne layout
What I've done: 
- Create promotions component with styles and container for redux
- Add promotions array to initial state and create reducer
- Make component responsive based on providen description
> [WDP210101-25] Add Promotions component

- README.md
I wrote a short explanation about our group project.
> Update 'Opis projektu'

- README.md
I wrote short story about our common rules and the project's structure.
> Update 'Conventions and good practices'

- src/components/common/FeedbackBox/FeedbackBox.js
- src/components/common/FeedbackBox/FeedbackBox.module.scss
- src/components/features/Feedback/Feedback.js
- src/components/features/Feedback/Feedback.module.scss
- src/components/features/Feedback/FeedbackContainer.js
- src/components/views/Homepage/Homepage.js
- src/redux/feedbackRedux.js
- src/redux/initialState.js
- src/redux/store.js
What to do:
- Create feedback component based on design
- Load content from state
- Dot of active slide should be orange
- Dots should have hover state
What I've done:
- Create feedback & feedbackBox componens, styles and container for redux
- Add reducer and load data from state
- Add required functionality for dots
> [WDP210101-33] Add Feedback component

- src/components/layout/Header/Header.js
- src/components/layout/MenuBar/MenuBar.js
- src/components/layout/MenuBar/MenuBarContainer.js
- src/redux/initialState.js
- src/redux/navbarRedux.js
- src/redux/store.js
What to do:
- MenuBar links must be generated automaticly based on data from initialState
What I've done:
- Add navbar data to initialState 
- Add navbar reducer & MenuBar container for redux
- Map over data from initialState go generate navbar links
Quick note:
- array of brands in initialState was modified because for the bug on master branch (someone forget to close array & objec)
> [WDP210101-45] Generate navbar links from state

- src/redux/initialState.js
- src/redux/productsRedux.js
In order to implement new functions for filtering and sorting the products, new Redux selectors are needed.
First one should enable the limit of the results according to the provided value - I implemented it by slicing the array (I also attempted to implement it with the method which filters the IDs - I leave it quoted for the judgement which one will work better or is more correct).
The other two are responsible for ascending and descending sorting by the provided parameter - I have added two functions which will sort the array accordingly. Probably during the development they can be adjusted if the sorting direction parameter will be also provided in some way, then selector could be more general, with additional argument in the function.
> [WDP210101-41] Add selectors for productsRedux

- src/components/features/ProductSearch/ProductSearch.module.scss
1. Changed the select category color to white on hover
2. Deleted border-radius property from category so that whole background color is being changed on hover.
3. I also changed transition time so that the color change would look smother.
> [WDP210101-48] Select a category bug

- src/components/common/ProductContainer/ProductContainer.js
- src/components/features/NewFurniture/NewFurniture.js
- src/components/features/NewFurniture/NewFurniture.module.scss
Task:
Improving readablilyty of Component NewFurniture.
Improvments: 
- New Component ProductConteiner, which create new boxex. This allow to move functions and huge amount of logic code to move into new area.
- Functions and whole logic moved into new component and code is much more cleaner
- Just Left little bit of logic which allow next Programmer who will be reading it to easly apply changes in this code.
> WDP210101-46 Poprawa czytelności New Furniture

- src/components/layout/Footer/Footer.js
- yarn.lock
1) Deleted the g+ icon from the footer.
> [WDP210101-59] Deleted the g+ icon.

- src/components/layout/MenuBar/MenuBar.module.scss
1.) Added transition property on hover of MenuBar components.
> [WDP210101-49] MenuBar bg transition

- src/components/layout/CompanyClaim/CompanyClaim.js
1. Changed client number in companyClaim element.
> [WDP210101-51] changed client number in companyClaim element.

- src/components/layout/TopBar/TopBar.js
- src/components/layout/TopBar/TopBar.module.scss
The goal of the task was to add dropdowns on hover with specified options to all three items in the Top Menu - I have implemented it using nested unordered lists. All the elements were styled consistently with the rest of the design.
> [WDP210101-55] Add dropdowns to Top Options section

- src/components/features/FeatureBoxes/FeatureBoxes.js
- src/components/features/FeatureBoxes/FeatureBoxes.module.scss
- src/components/features/Promotions/Promotions.module.scss
task:
Client want to make animation on FeatureBox and Promotion Boxes. Best one is appearance that should come out of the page.
My job:
FurnitureBox:
I added class to boxes and make keyframes with animations. Then to every box i applied that animation.
PromotionBox: 
Also i added class and make animation for every box from diffrend direction. I think animation is too fast but looks fine so i leave it to review.
> [WDP210101-52] Wyłanianie się elementów

- src/components/views/ProductList/ProductList.js
- src/components/views/ProductList/ProductList.module.scss
- src/redux/initialState.js
We need to code the top part according to the provided design of the section to fulfil the task.
I have built the section structure as simple as possible thanks to what Bootstrap offers, with just a little additional CSS.
Banner is simply styled text with flex for the positioning.
For the Breadcrumbs element I have tried implementing various components available that rely on modifying Router, but none have worked so far for me, so I have temporarily chosen the method which will allow to show the customer the final effect, and full functionality will be added after I master one of the packages.
> [WDP210101-40] Add banner and breadcrumbs to products list

- src/components/views/ProductList/ProductList.js
- src/components/views/ProductList/ProductList.module.scss
In this task we need to code the design from the layout the Header and Filtres sections of the Product List.
Selects for the Header need to be functional - dropdowns received the desired options.
For the Filtres I didn't manage to add the working range slider for the price - I am not able to install any package to import to ready solutions. For the last sizes filter I am stuck with displaying it inline.
I am also aware that for the final product it would be better to code every above-mentioned module in the separate component and provide its options in initialState with accurate rendering.
> [WDP210101-42] Add Header and Filtres to Product List section

- src/App.js
- src/components/common/Button/Button.module.scss
- src/components/layout/Footer/Footer.js
- src/components/layout/TopBar/TopBar.js
- src/components/views/Login/Login.js
- src/components/views/Login/Login.module.scss
The goal of the task is to add a simple login form on the separate site in the Router. It requires separate component available in Router and minor adjustments to the files pointing at Login - TopBar and Footer. In Button variants there is included new simplified style inheriting from the "main", which will be reused in the Registration form as well. Styling of the form inherits the design of the components which are already in use.
> [WDP210101-56] Login form

- src/App.js
- src/components/common/Button/Button.module.scss
- src/components/layout/Footer/Footer.js
- src/components/layout/TopBar/TopBar.js
- src/components/views/Login/Login.js
- src/components/views/Login/Login.module.scss
- src/components/views/Register/Register.js
- src/components/views/Register/Register.module.scss
The goal of the task is to add a simple registration form on the separate site in the Router. It requires separate component available in Router and minor adjustments to the TopBar pointing at Register. In Button variants there is included new simplified style inheriting from the "main". Styling of the form inherits the design of the components which are already in use.
> [WDP210101-57] Registration form

- src/App.js
Task covers extending functionality of products list subpage. It should render furniture list. 
I've added x and y.
> WDP210101-58
